config/routes.rb
Rails.application.routes.draw do
  root 'enduser/tops#top'

  namespace :enduser do
    devise_for :endusers
    resources :tops, only: [:top]
    get 'tops/top', to: 'tops#top'
    resources :cds, only: [:index, :show]
    get 'search', to: 'cds#search'
    resources :endusers, only: [:show, :edit, :leave, :update, :destroy] do
    get 'leave', to: 'endusers#leave', on: :member
    end
    resources :cart_items, only: [:index, :create, :destroy, :update]
    resources :delivery_addresses, only: [:new, :create, :destroy]
    resources :orders ,only: [:index, :show, :create]
    get 'order_confirmations/thanks', to: 'order_confirmations#thanks'
    resources :order_confirmations, only: [:index, :thanks]
    resources :inquires, only: [:form, :create]
    get 'inquires/form', to: 'inquires#form'
    resources :reviews, only: [:create, :destroy, :edit, :update]
    #resources :favorites, only: [:create, :destroy]
    post 'favorites/:cd_id', to:'favorites#create', as: 'create_favorites'
    delete  'favorites/:cd_id', to:'favorites#destroy', as:'destroy_favorites'
  end

  namespace :endusers do
    devise_for :endusers, :controller => {

    }
  end


  namespace :admins do
    devise_for :admins, :controller => {

    }
  end

  namespace :admin do
    resources :endusers, only: [:index, :show, :edit, :update, :destroy] do
    get 'leave', to: 'endusers#leave', on: :member
    get 'orders', to: 'endusers#order', on: :member
    end
    resources :cds
    get 'search', to: 'cds#search'
    resources :orders ,only: [:index, :show, :update]
    resources :genres, only: [:new, :destroy, :index, :create]
    resources :labels, only: [:create, :destroy, :index]
    resources :artists, only: [:create, :destroy, :index]
    resources :arrival_cds, only: [:new, :index, :create]
    resources :reviews, only: [:destroy, :edit, :update]
    resources :inquires, only: [:index, :show, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/endusers_controller.rb
class Admin::EndusersController < ApplicationController
  before_action :authenticate_admins_admin!

  def index
    @users = Enduser.page(params[:page]).reverse_order
  end

  def show
    @user = Enduser.find(params[:id])
  end

  def edit
    @user = Enduser.find(params[:id])
  end

  def leave
    @user = Enduser.find(params[:id])
  end

  def order
    @user = Enduser.find(params[:id])
    @orders = @user.orders
  end

  def update
    @user = Enduser.find(params[:id])
    if @user.update(enduser_params)
         flash[:notice] = "You have updated successfully."
         redirect_to admin_enduser_path(@user.id)
      else
         flash[:notice] = "error"
         redirect_to edit_admin_enduser_path(@user.id)
      end
  end

  def destroy
    @user = Enduser.find_by(id:params[:id])
    @user.destroy
      redirect_to admin_endusers_path
  end

  private
    def enduser_params
      params.require(:enduser).permit(:first_name,:last_name,:reading_first_name,:reading_last_name,:postcode,:address,:phone_number)
  end

end

app/controllers/enduser/cart_items_controller.rb
class Enduser::CartItemsController < ApplicationController
  before_action :authenticate_endusers_enduser!

  def index
    #金額表示関係
    @tax = TaxRate.find(1)
    @postage = Postage.find(1)
    #カート基本情報
    @user = current_endusers_enduser
    @cart_items = @user.cart_items.all
  end

  def create
    @cd = Cd.find(params[:id])
    @cart = CartItem.new
    @cart.enduser_id = current_endusers_enduser.id
    @cart.cd_id = @cd.id
    @cart.save
    redirect_to enduser_cart_items_path
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to enduser_cart_items_path
  end

  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to enduser_cart_items_path
  end

  private
  def cart_item_params
    params.require(:cart_item).permit(:enduser_id,:cd_id,:item_count)
  end

end

app/controllers/enduser/cds_controller.rb
class Enduser::CdsController < ApplicationController

PER = 12

def index
 @cds = Cd.page(params[:page]).per(PER)
 @cd = Cd.new
 @q = Cd.ransack(params[:q])
 cds = @q.result(distinct: true)
end

def search
   @q = Cd.search(search_params)
   @cds = @q.result(distinct: true)
end

def show
 @tax = TaxRate.find(1)
 #CDの情報取得
 @cd = Cd.find(params[:id])
 @discs = @cd.discs
 #cdに紐付いた情報の取得
 @genre = @cd.genre
 @artist = @cd.artist
 @label = @cd.label
  #cart_itemsにcdを追加
 @Cart_items = CartItem.new
 @favorit = Favorit.new
 #詳細ページが開かれると閲覧数のカラムに＋１
 @cd.view_number += 1
 @cd.save
 #view/enduser/cd/:idのreviewの投稿からform_withで飛んでくる
 @review = @cd.reviews.build
 @reviews = @cd.reviews  #controller/enduser/review/def createに飛ぶ
end

def new
 @cart = Cart_items.new
end

private
def search_params
 params.require(:q).permit!
end

end

app/controllers/enduser/deliverly_addresses_controller.rb
class Enduser::DeliverlyAddressesController < ApplicationController

	def new
	end

	def create
	end

	def destroy

	end
end

app/controllers/enduser/delivery_addresses_controller.rb
class Enduser::DeliveryAddressesController < ApplicationController
	before_action :authenticate_endusers_enduser!

	def new
		@delivery_address = DeliveryAddress.new
	end

	def create
		@delivery_address = DeliveryAddress.new(delivery_address_params)
		@delivery_address.enduser_id =  current_endusers_enduser.id
		if @delivery_address.save
		  redirect_to enduser_enduser_path(current_endusers_enduser.id)
		else
			render 'new'
		end
	end

	def destroy
		delivery_address = DeliveryAddress.find(params[:id])
        delivery_address.destroy
        redirect_to enduser_enduser_path(current_endusers_enduser.id)
	end

	private

    def delivery_address_params
      params.require(:delivery_address).permit(:enduser_id, :postcode, :address, :first_name, :last_name)
    end
end

app/controllers/enduser/endusers_controller.rb
class Enduser::EndusersController < ApplicationController
	before_action :authenticate_endusers_enduser!

	def show
        @enduser = Enduser.find(params[:id])
      if current_endusers_enduser.id != @enduser.id
		redirect_to root_path
	  end
    end

   def edit
		@enduser = Enduser.find(params[:id])
	 if current_endusers_enduser.id != @enduser.id
		redirect_to enduser_enduser_path(current_endusers_enduser)
	 end
   end


	def leave
		@enduser = Enduser.find(params[:id])

	end


   def update
		@enduser = Enduser.find(params[:id])
     if @enduser.update(enduser_params)
         flash[:notice] = 'successfully'
         redirect_to enduser_enduser_path(current_endusers_enduser.id)
     else
    	render 'edit'
    end
   end



	def destroy
		@enduser = Enduser.find(params[:id])
        @enduser.destroy
        redirect_to root_path
	end


private

	def enduser_params
	    params.require(:enduser).permit(:first_name, :last_name, :reading_first_name, :reading_last_name, :postcode, :address, :phone_number, :email)
	end

end

app/controllers/enduser/favorites_controller.rb
class Enduser::FavoritesController < ApplicationController
	before_action :authenticate_endusers_enduser!

  def create
    @favorit = Favorit.create( enduser_id:current_endusers_enduser.id,  cd_id: params[:cd_id])
    #@favorit.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @favorit = Favorit.find_by(cd_id: params[:cd_id], enduser_id: current_endusers_enduser.id)
    @favorit.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/enduser/inquires_controller.rb
class Enduser::InquiresController < ApplicationController
	def form
		@inquire = Inquire.new
	end
	def create
		@inquire = Inquire.new(inquire_params)
		@inquire.save
		redirect_to root_path
	end

	private

	def inquire_params
		params.require(:inquire).permit(:title, :mail, :name, :body)
	end
end

app/controllers/enduser/order_confirmations_controller.rb
class Enduser::OrderConfirmationsController < ApplicationController
	before_action :authenticate_endusers_enduser!

	def index
		@order = Order.new
		@cart_items = current_endusers_enduser.cart_items.all
		@tax = TaxRate.find(1)
		@postage = Postage.find(1)
	end

	def thanks
	end
end

app/controllers/enduser/orders_controller.rb
class Enduser::OrdersController < ApplicationController
	before_action :authenticate_endusers_enduser!

	def index
		@orders = current_endusers_enduser.orders.all.page(params[:page]).per(10)
		@enduser = Enduser.find(current_endusers_enduser.id)
	end

	def show
		@order = Order.find(params[:id])
	end

	def create
		@tax = TaxRate.find(1)
		@postage = Postage.find(1)
		order = Order.new(order_params)
		cart_items = current_endusers_enduser.cart_items.all

        #エンドユーザー外部キー情報の受け渡し
        order.enduser_id = current_endusers_enduser.id

        #ラジオボタンの情報受け取り　１：Deliveryaddressからの選択
        if params[:address_button].to_i == 1

            #order_confomationで選んだdelivey_addressの情報を受け取る
        	delivery_address = DeliveryAddress.find_by(id: params[:address_id])  #find(params[:order][:address)でも可

        	if DeliveryAddress.find_by(id: params[:address_id]).present?
				order.first_name = delivery_address.first_name
				order.last_name = delivery_address.last_name
				order.postcode = delivery_address.postcode
				order.address = delivery_address.address
				order.postage = @postage.postage
	    	end
	    #ラジオボタンの情報受け取り　２：投稿ホームからの受け取り
		elsif  params[:address_button].to_i == 2
           order.postage = @postage.postage
           new_address = DeliveryAddress.new
		   new_address.enduser_id = current_endusers_enduser.id
		   new_address.first_name = order.first_name
		   new_address.last_name = order.last_name
		   new_address.postcode = order.postcode
		   new_address.address = order.address
		   new_address.save
        else
		end

		#購入商品情報と購入数、小計を保存
		cart_items.each do |c|
			# binding.pry
			order_product = order.order_products.build
			order_product.cd_id = c.cd.id
			order_product.order_count = c.item_count
			order_product.subtotal_price = c.cd.price * c.item_count
			order_product.order_tax_rate = @tax.tax_rate
		end

		#総計を計算
		order.total_price = 0
		cart_items.each do |c|
			order.total_price += c.cd.price * @tax.tax_rate * c.item_count
		end
		order.total_price += @postage.postage

		if order.save
			cart_items.each do |c|
				if c.cd.stock <= 0
					c.cd.sell_status = 0
				else
					c.cd.sell_status = 1
				end
	         c.cd.save
             c.destroy
            end
		  redirect_to enduser_order_confirmations_thanks_path
		else
		  flash[:create_false]  = "配送先を指定してください"
		  redirect_to enduser_order_confirmations_path
		end

	end

	private
	def order_params
		params.require(:order).permit(:first_name, :last_name, :postcode, :address, :total_price, :postage)
	end

end

app/controllers/enduser/reviews_controller.rb
class Enduser::ReviewsController < ApplicationController
	before_action :authenticate_endusers_enduser!

	def create
		#controller/enduuser/cdのdef showから飛んでくる
	    @review = Review.new(review_params)
	    @cd = Cd.find(@review.cd_id)
		@reviews = @cd.reviews
	    @review.enduser_id = current_endusers_enduser.id
        if @review.save
        	flash[:create] = "レビューが追加されました"
        	#enduser/reviews/index.js.erbに飛ぶ
            render "enduser/reviews/index.js.erb"
        else
        	render "enduser/reviews/rollback.js.erb"
        end
	end

	def destroy
#		@review = Review.find_by(cd_id: params[:id], enduser_id: current_endusers_enduser.id)
	    @review = Review.find(params[:id])
	    #if @review.enduser_id ==current_endusers_enduser.id
		@review.destroy
		#end
		redirect_to enduser_cd_path(@review.cd)
	end

	def edit
		@review = Review.find(params[:id])
	end

	def update
		@review = Review.find(params[:id])
		if @review.update(review_params)
			flash[:update] = "レビューが更新されました"
			redirect_to enduser_cd_path(@review.cd)
	    else
	    	render :edit
	    end
	end

	private
    def review_params
      params.require(:review).permit(:cd_id, :review_title, :review_body)
    end
end

app/controllers/enduser/tops_controller.rb
class Enduser::TopsController < ApplicationController
	def top
		#CDの詳細ページの開かれた回数を多い順に並べ替えして上から４つ取得する
		@all_ranks = Cd.find(Cd.order(view_number: :desc).limit(4).pluck(:id))
	end
end

app/controllers/endusers/confirmations_controller.rb
# frozen_string_literal: true

class Endusers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/endusers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Endusers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/endusers/passwords_controller.rb
# frozen_string_literal: true

class Endusers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/endusers/registrations_controller.rb
# frozen_string_literal: true

class Endusers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  def after_sign_up_path_for(resource)
    case resource
        when Enduser
          new_address = DeliveryAddress.new
          new_address.enduser_id = current_endusers_enduser.id
          new_address.first_name = current_endusers_enduser.first_name
          new_address.last_name = current_endusers_enduser.last_name
          new_address.postcode = current_endusers_enduser.postcode
          new_address.address = current_endusers_enduser.address
          new_address.save
          root_path
        end
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/endusers/sessions_controller.rb
# frozen_string_literal: true

class Endusers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/endusers/unlocks_controller.rb
# frozen_string_literal: true

class Endusers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/endusers_helper.rb
module EndusersHelper
end

app/views/enduser/endusers/edit.html.erb
<div>
<% if @enduser.errors.any? %>
          <div id="error_explanation" class="alert alert-danger">
            <p><%= @enduser.errors.count %>errors prohibited this obj from being saved</p>
           <ul>
              <% @enduser.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
           </ul>
          </div>
<% end %>
</div>






<div class="editbody">


<h2>ユーザー情報編集</h2>

<%= form_for(@enduser, url:enduser_enduser_path) do |f| %>

	<div class="nameform" style="float:left;">
	 	<%= f.label :苗字 %><br />
	 	<%= f.text_field :first_name %>
  </div>



    <div class="nameform" style="float:left;">
	 	<%= f.label :名前 %><br />
	 	<%= f.text_field :last_name %>
    </div>


        <div style="clear:both;">
        </div>

    <div style="float:left;">
       <%= f.label :苗字「フリガナ」 %><br />
       <%= f.text_field :reading_first_name, autofocus: true, autocomplete: "苗字[フリガナ]" %>
 　 </div>

    <div style="float:left;">
       <%= f.label :名前「フリガナ」 %><br />
       <%= f.text_field :reading_last_name, autofocus: true, autocomplete: "名前[フリガナ]" %>
 　 </div>


    <div class="form" style="clear:both;">
       <%= f.label :郵便番号 %><br />
       <%= f.text_field :postcode, autofocus: true, autocomplete: "郵便番号" %>
 　 </div>


    <div class="form">
      <%= f.label :住所 %><br />
      <%= f.text_area :address, autofocus: true, autocomplete: "住所"%>
 　 </div>

    <div class="form">
      <%= f.label :電話番号 %><br />
      <%= f.text_field :phone_number, autofocus: true, autocomplete: "電話番号"%>
 　 </div>


    <div class="form">
      <%= f.label :Eメール %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "Eメール"%>
 　 </div>

    <div class="actions">
    <h3><%= f.submit "更新" %></h3>
    </div>

<% end %>

</div>

app/views/enduser/endusers/leave.html.erb
<div class="contaiber">
	　　<div class="row">
			<div class="taikai">
				<h2>本当に退会しますか？</h2>
			</div>

			<ul class="inline">

				<li class="font-size"><%= link_to "はい", enduser_enduser_path(@enduser.id), class:"btn-lg btn-danger destroy", method: :delete, "data-confirm" => "本当に削除しますか？？" %></li>

				<li><%= link_to "いいえ", enduser_enduser_path(current_endusers_enduser.id) %></li>

			</ul>
	    </div>
</div>

app/views/enduser/endusers/show.html.erb
<div class="container cd-show">
  <div class="row">
    <div class="col-lg-12">
      <h2>マイページ</h2>
      <br>
      <div class="col-lg-9">
        <table class="table table-border">
          <tbody>
            <tr>
              <th><h3>名前：</p></th>
              <th><h3><%= @enduser.first_name %><%= @enduser.last_name %></h3></th>
            </tr>
            <tr>
              <th><h3>郵便番号：</h3></th>
              <th><h3>〒<%= @enduser.postcode %></h3></th>
            </tr>
            <tr>
              <th><h3>住所：</h3></th>
              <th><h3><%= @enduser.address %></h3></th>
            </tr>
            <tr>
              <th><h3>電話番号：</h3></th>
              <th><h3><%= @enduser.phone_number %></h3></th>
            </tr>
            <tr>
              <th><h3>メールアドレス：</h3></th>
              <th><h3><%= @enduser.email %></h3></th>
            </tr>
          </tbody>
        </table>
        <br>
        <br>
        <table class="table">
          <h4>配送先住所一覧</h4>
          <tbody>
            <% @enduser.delivery_addresses.each do |a| %>
              <tr>
                <th><h5>郵便番号：</h5></th>
                <th><h5>〒<%= a.postcode %></h5></th>
                <th><h5>住所：</h5><th>
                <th><h5><%= a.address %></h5><th>
                <th><%= link_to "削除", enduser_delivery_address_path(a.id), class:"btn-sm btn-danger destroy", method: :delete, "data-confirm" => "本当に削除しますか？？" %></th>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <br>
      <br>
      <div class="col-lg-3">
        <div class="right-box">
          <ul class="list-group">
            <li class="list-group-item"><h4 class="center"><%= link_to "登録情報の編集", edit_enduser_enduser_path %></h4></li>
            <li class="list-group-item"><h4 class="center"><%= link_to "購入履歴", enduser_orders_path %></h4></li>
            <li class="list-group-item"><h4 class="center"><%= link_to "配送先住所を追加", new_enduser_delivery_address_path %></h4></li>
            <li class="list-group-item"><h5 class="center"><%= link_to "退会", leave_enduser_enduser_path %></h5></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
