config/routes.rb
Rails.application.routes.draw do
  root 'enduser/tops#top'

  namespace :enduser do
    devise_for :endusers
    resources :tops, only: [:top]
    get 'tops/top', to: 'tops#top'
    resources :cds, only: [:index, :show]
    get 'search', to: 'cds#search'
    resources :endusers, only: [:show, :edit, :leave, :update, :destroy] do
    get 'leave', to: 'endusers#leave', on: :member
    end
    resources :cart_items, only: [:index, :create, :destroy, :update]
    resources :delivery_addresses, only: [:new, :create, :destroy]
    resources :orders ,only: [:index, :show, :create]
    get 'order_confirmations/thanks', to: 'order_confirmations#thanks'
    resources :order_confirmations, only: [:index, :thanks]
    resources :inquires, only: [:form, :create]
    get 'inquires/form', to: 'inquires#form'
    resources :reviews, only: [:create, :destroy, :edit, :update]
    #resources :favorites, only: [:create, :destroy]
    post 'favorites/:cd_id', to:'favorites#create', as: 'create_favorites'
    delete  'favorites/:cd_id', to:'favorites#destroy', as:'destroy_favorites'
  end

  namespace :endusers do
    devise_for :endusers, :controller => {

    }
  end


  namespace :admins do
    devise_for :admins, :controller => {

    }
  end

  namespace :admin do
    resources :endusers, only: [:index, :show, :edit, :update, :destroy] do
    get 'leave', to: 'endusers#leave', on: :member
    get 'orders', to: 'endusers#order', on: :member
    end
    resources :cds
    get 'search', to: 'cds#search'
    resources :orders ,only: [:index, :show, :update]
    resources :genres, only: [:new, :destroy, :index, :create]
    resources :labels, only: [:create, :destroy, :index]
    resources :artists, only: [:create, :destroy, :index]
    resources :arrival_cds, only: [:new, :index, :create]
    resources :reviews, only: [:destroy, :edit, :update]
    resources :inquires, only: [:index, :show, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/arrival_cd.rb
class ArrivalCd < ApplicationRecord
	belongs_to :cd
	validates :arrival_count, :arrival_date, presence: true
end

app/models/artist.rb
class Artist < ApplicationRecord

has_many :cds

validates :name, presence: true
 end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :enduser
	belongs_to :cd
end

app/models/cd.rb
class Cd < ApplicationRecord
	belongs_to :genre
	belongs_to :label
	belongs_to :artist
	has_many :favorits
	has_many :favorited_endusers, through: :favorits, source: :enduser
	has_many :reviews
	has_many :cart_items
	has_many :order_products
	has_many :arrival_cds
	has_many :discs
	accepts_nested_attributes_for :discs, reject_if: :all_blank, allow_destroy: true

	attachment :image

  enum type: { シングル: 0,アルバム: 1 }
  enum sell_status: { 販売停止: 0, 販売中: 1 }
  self.inheritance_column = :_type_disabled
  acts_as_paranoid

	validates :title, presence: true
	validates :type, presence: true
	validates :price, presence: true
	validates :release_date, presence: true

  def stock
	  ar = ArrivalCd.group(:cd_id).where(cd_id: id).sum(:arrival_count)  # id = cd.id
	  odr  = OrderProduct.group(:cd_id).where(cd_id: id).sum(:order_count)
	  ar[id].to_i - odr[id].to_i  #id = cd.id
  end
end

app/models/disc.rb
class Disc < ApplicationRecord
	belongs_to :cd
	has_many :song_titles
	accepts_nested_attributes_for :song_titles, reject_if: :all_blank, allow_destroy: true

	validates :disc_number, presence: true
end

app/models/enduser.rb
class Enduser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :reading_first_name, presence: true
  validates :reading_last_name, presence: true
  validates :postcode, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true



  paginates_per 30
  acts_as_paranoid

  has_many :delivery_addresses
  has_many :reviews
  has_many :favorits
  has_many :cart_items
  has_many :orders

  def already_favorited?(cd)
    self.favorits.exists?(cd_id: cd.id)
  end

end

app/models/favorit.rb
class Favorit < ApplicationRecord
	belongs_to :enduser
	belongs_to :cd
	validates_uniqueness_of :cd_id, scope: :enduser_id
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :cds

	validates :name, presence: true



end

app/models/inquire.rb
class Inquire < ApplicationRecord
  validates :mail, presence: true
  validates :title, presence: true
end

app/models/label.rb
class Label < ApplicationRecord

	has_many :cds

	validates :name, presence: true



end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :enduser
	has_many :order_products
	enum status: { 受付中: 0,配送中:1,受け取り済み:2 }
	validates :address, :first_name, :last_name, :postcode, :address, :total_price, :postage, presence: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
	belongs_to :order
	belongs_to :cd
end

app/models/postage.rb
class Postage < ApplicationRecord
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :enduser
	belongs_to :cd

	validates :review_title, presence: true
	validates :review_body, presence: true
end

app/models/song_title.rb
class SongTitle < ApplicationRecord
	belongs_to :disc

	validates :song, presence: true
end

app/models/tax_rate.rb
class TaxRate < ApplicationRecord
end

app/controllers/admin/inquires_controller.rb
class Admin::InquiresController < ApplicationController
	before_action :authenticate_admins_admin!

	def index
		@inquires = Inquire.all
	end

	def show
		@inquire = Inquire.find(params[:id])
	end

	def update
		inquire = Inquire.find(params[:id])
		inquire.update(inquire_params)
		InquiryMailer.send_when_admin_reply(inquire)
		redirect_to admin_inquires_path

	end



	private
	def inquire_params
		params.require(:inquire).permit(:re_title, :re_body)
	end


end

app/controllers/enduser/inquires_controller.rb
class Enduser::InquiresController < ApplicationController
	def form
		@inquire = Inquire.new
	end
	def create
		@inquire = Inquire.new(inquire_params)
		@inquire.save
		redirect_to root_path
	end

	private

	def inquire_params
		params.require(:inquire).permit(:title, :mail, :name, :body)
	end
end

app/helpers/cds_helper.rb
module CdsHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/inquires_helper.rb
module InquiresHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/admin/inquires/index.html.erb
<div class="toiawase">

<h2>問い合わせ一覧</h2>



<div class="contaiber">

	<div class="row">

		<div class="col-lg-10">

	   		<table class="table table-striped">
				<thead>

					 <tr>
						<th>日付</th>
						<th>ユーザー名</th>
						<th>メールアドレス</th>
						<th>件名</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
       				<% @inquires.each do |inquire| %>
       				<tr>

					        <td>
					        	<%= inquire.created_at.strftime("%Y-%m-%d %H:%M") %>
					        </td>
					        <td>
					        	<%= inquire.name %>
					        </td>
					        <td>
					             <%= inquire.mail %>
					        </td>
					        <td>
					        	 <%= inquire.title %>
					        </td>
					        <td>
					             <%= link_to "詳細", admin_inquire_path(inquire) %>
					       </td>

					    </tr>
                     <% end %>

		       </tbody>
   			</table>
   		</div>
   	  </div>
   	</div>
</div>

</div>

app/views/admin/inquires/inquire_mail.html.erb
<hi>お問い合わせ詳細</hi>


<p>日付: </p>
<p>タイトル: <%= @inquire.title %></p>
<p>メールアドレス: <%= @inquire.mail %></p>
<p>ユーザー名: <%= @inquire.name %></p>
<p>本文: <%= @inquire.body %></p>

app/views/admin/inquires/inquire_mail.text.erb
Inquire#inquire_mail

<%= @greeting %>, find me in app/views/inquire_mailer/inquire_mail.text.erb

app/views/admin/inquires/show.html.erb
<div class="toiawaeshow">

<h2>問い合わせ詳細</h2>
<br>
<br>




	<table>
		<thead>
			<tr>
				<th>

				</th>
				<th>

				</th>
			</tr>
		</thead>

        <tbody>

        	<tr>
        	    <td>日付:</td>
        		<td><%= @inquire.created_at.strftime("%Y-%m-%d %H:%M") %></td>
        	</tr>
        	<tr>
        		<td>タイトル:</td>
        		<td><%= @inquire.title %></td>
        	</tr>
        	<tr>
        		<td>メールアドレス:</td>
        		<td><%= @inquire.mail %></td>
        	</tr>
        	<tr>
        		<td>ユーザー名:</td>
        		<td><%= @inquire.name %></td>
        	</tr>
        	<tr>
        		<td>詳細</td>
        	</tr>
        	<tr>
        		<td><%= @inquire.body %></td>
        	</tr>
        </tbody>
    </table>




<%= form_for(@inquire, url:admin_inquire_path) do |f| %>
   <h2>返信フォーム</h2>
     <br>
        <h4>件名</h4>
        <p><%= f.text_field :re_title %></p>
     <br>
        <h4>本文</h4>
        <p><%= f.text_area :re_body %></p>
     <br>
     <div class="actions">
       <h3><%= f.submit "送信" %></h3>
    

<% end %>
</div>