config/routes.rb
Rails.application.routes.draw do
  root 'enduser/tops#top'

  namespace :enduser do
    devise_for :endusers
    resources :tops, only: [:top]
    get 'tops/top', to: 'tops#top'
    resources :cds, only: [:index, :show]
    get 'search', to: 'cds#search'
    resources :endusers, only: [:show, :edit, :leave, :update, :destroy] do
    get 'leave', to: 'endusers#leave', on: :member
    end
    resources :cart_items, only: [:index, :create, :destroy, :update]
    resources :delivery_addresses, only: [:new, :create, :destroy]
    resources :orders ,only: [:index, :show, :create]
    get 'order_confirmations/thanks', to: 'order_confirmations#thanks'
    resources :order_confirmations, only: [:index, :thanks]
    resources :inquires, only: [:form, :create]
    get 'inquires/form', to: 'inquires#form'
    resources :reviews, only: [:create, :destroy, :edit, :update]
    #resources :favorites, only: [:create, :destroy]
    post 'favorites/:cd_id', to:'favorites#create', as: 'create_favorites'
    delete  'favorites/:cd_id', to:'favorites#destroy', as:'destroy_favorites'
  end

  namespace :endusers do
    devise_for :endusers, :controller => {

    }
  end


  namespace :admins do
    devise_for :admins, :controller => {

    }
  end

  namespace :admin do
    resources :endusers, only: [:index, :show, :edit, :update, :destroy] do
    get 'leave', to: 'endusers#leave', on: :member
    get 'orders', to: 'endusers#order', on: :member
    end
    resources :cds
    get 'search', to: 'cds#search'
    resources :orders ,only: [:index, :show, :update]
    resources :genres, only: [:new, :destroy, :index, :create]
    resources :labels, only: [:create, :destroy, :index]
    resources :artists, only: [:create, :destroy, :index]
    resources :arrival_cds, only: [:new, :index, :create]
    resources :reviews, only: [:destroy, :edit, :update]
    resources :inquires, only: [:index, :show, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :enduser
	has_many :order_products
	enum status: { 受付中: 0,配送中:1,受け取り済み:2 }
	validates :address, :first_name, :last_name, :postcode, :address, :total_price, :postage, presence: true
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	before_action :authenticate_admins_admin!

	def index
		@orders = Order.page(params[:page]).per(20)
	end

	def show
		@order = Order.find(params[:id])
	end

	def update
		@order = Order.find(params[:id])
		if @order.update(order_params)
			flash[:success_update]  = "アップデートに成功しました"
		   redirect_to admin_orders_path
	    end
	end

	private
    def order_params
      params.require(:order).permit(:status)
    end


end

app/controllers/enduser/orders_controller.rb
class Enduser::OrdersController < ApplicationController
	before_action :authenticate_endusers_enduser!

	def index
		@orders = current_endusers_enduser.orders.all.page(params[:page]).per(10)
		@enduser = Enduser.find(current_endusers_enduser.id)
	end

	def show
		@order = Order.find(params[:id])
	end

	def create
		@tax = TaxRate.find(1)
		@postage = Postage.find(1)
		order = Order.new(order_params)
		cart_items = current_endusers_enduser.cart_items.all

        #エンドユーザー外部キー情報の受け渡し
        order.enduser_id = current_endusers_enduser.id

        #ラジオボタンの情報受け取り　１：Deliveryaddressからの選択
        if params[:address_button].to_i == 1

            #order_confomationで選んだdelivey_addressの情報を受け取る
        	delivery_address = DeliveryAddress.find_by(id: params[:address_id])  #find(params[:order][:address)でも可

        	if DeliveryAddress.find_by(id: params[:address_id]).present?
				order.first_name = delivery_address.first_name
				order.last_name = delivery_address.last_name
				order.postcode = delivery_address.postcode
				order.address = delivery_address.address
				order.postage = @postage.postage
	    	end
	    #ラジオボタンの情報受け取り　２：投稿ホームからの受け取り
		elsif  params[:address_button].to_i == 2
           order.postage = @postage.postage
           new_address = DeliveryAddress.new
		   new_address.enduser_id = current_endusers_enduser.id
		   new_address.first_name = order.first_name
		   new_address.last_name = order.last_name
		   new_address.postcode = order.postcode
		   new_address.address = order.address
		   new_address.save
        else
		end

		#購入商品情報と購入数、小計を保存
		cart_items.each do |c|
			# binding.pry
			order_product = order.order_products.build
			order_product.cd_id = c.cd.id
			order_product.order_count = c.item_count
			order_product.subtotal_price = c.cd.price * c.item_count
			order_product.order_tax_rate = @tax.tax_rate
		end

		#総計を計算
		order.total_price = 0
		cart_items.each do |c|
			order.total_price += c.cd.price * @tax.tax_rate * c.item_count
		end
		order.total_price += @postage.postage

		if order.save
			cart_items.each do |c|
				if c.cd.stock <= 0
					c.cd.sell_status = 0
				else
					c.cd.sell_status = 1
				end
	         c.cd.save
             c.destroy
            end
		  redirect_to enduser_order_confirmations_thanks_path
		else
		  flash[:create_false]  = "配送先を指定してください"
		  redirect_to enduser_order_confirmations_path
		end

	end

	private
	def order_params
		params.require(:order).permit(:first_name, :last_name, :postcode, :address, :total_price, :postage)
	end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class = "left-space">

	<% if flash[:success_update] %>
		<div class = "success_message">
		    <%= flash[:success_update] %>
		</div>
	<% end %>

	<% sum_order = 0 %>
	<% @orders.each do |o| %>
		<% sum_order = o.total_price/(1.1) - 500 %>
	<% end %>

	<h2>受注履歴一覧（全ユーザー）</h2>

	<div class="contaiber">
	　　<div class="row">
		  <div class="col-lg-10">
			<table class="table">
			　　<thead>
				  <tr>
				  	<h3>売上合計：<%= sum_order.to_i %>円</h3>
				  </tr>
			   </thead>
				<tbody>
				  <% @orders.each do |order| %>
				     <tr>
						  <th>
						  	<%= link_to admin_order_path(order.id) do %>
						  	<%= order.created_at.strftime("%Y-%m-%d %H:%M") %>
						  	<% end %>
						  </th>
						  <th>
							    <a>
							    	<%= link_to admin_order_path(order.id) do %>購入合計個数：
							        <% sum = 0 %>
									    <% order.order_products.each do |product| %>
									      <% sum += product.order_count %>
									    <% end %>
							        <%= sum %>個
							        <% end %>
							    </a>
						  </th>
						  <th>
								<a>
									<%= link_to admin_order_path(order.id) do %>
									購入合計金額：<%= order.total_price %>円
									<% end %>
								</a>
						  </th>
						  <%= form_for order, url: admin_order_path(order.id), method: :patch do |f| %>
							<th>
								<%= f.select :status, Order.statuses.keys.to_a, {} %>
							</th>
							<th>
								<%= f.submit 'ステータス更新', :class=>"btn btn-primary  btn-block" %>
							</th>
						  <% end %>
						</tr>
					<% end %>
				</tbody>
			</table>
			<%= paginate @orders %>
		  </div>
		</div>
	</div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
	<h3>購入者：<%= @order.first_name %><%= @order.last_name %></h3>

	<h3>購入日：<%= @order.created_at.strftime("%Y-%m-%d %H:%M") %></h3>

	<h3>送付先：<%= @order.address %></h3>

	<h3>ステータス：<%= @order.status %></h3>
  </div>
</div>
<div class="container">
　　<div class="row">
		<table class="table">
		　　<thead></thead>
			<tbody>
				<% @order.order_products.each do |product| %>

				    <th><%= product.cd.title %></th>

					<th><%= product.order_count %>個</th>

					<th>小計：￥<%= product.subtotal_price %></th>

				  </tr>
				<% end %>
					<tr>
						<th>購入金額合計：<%= @order.total_price %>(税込)</th>

						<th>送料：￥<%= @order.postage %>を含む</th>
					</tr>
			</tbody>
		</table>
	</div>
</div>